### ISSUE TITLE
D2.2.4 - Ingestion software for LSST DR1 (Rescope DP0.2 and document process and weakness/ lessons learned)

### ISSUE THREAD

**Issue by markgbeckett** [lsst-uk/ukdac1#114] opened 2022-09-26 09:52 UTC
- Delay until March’23 (Change Request)
- Potentiallly needs to be delayed/ rescoped
- Not just software – scripts, processes, resources.

**Comment by tms-epcc** [comment] 2022-10-06 15:20
Note this is a duplicate of https://app.zenhub.com/workspaces/lsstuk-dac-5f325f8cf1760d0016c4abfb/issues/lsst-uk/dataingestpublication-wp2.2/5

**Comment by tms-epcc** [comment] 2023-02-03 11:37
03/FEB/23
- Change request [C058](https://lsst-uk.atlassian.net/wiki/download/attachments/751108134/C058-WP2.2_data_ingestion.pdf?version=2&modificationDate=1675423966721&cacheVersion=1&api=v2) approved at 23/JAN/23 Exec Group.
- CR moved due date from 30/NOV/22 (PM41) to 31/DEC/23 (PM54)

**Comment by tms-epcc** [comment] 2024-01-04 16:37
04/JAN/24
- at DAC meeting @markgbeckett discussed subsuming this into the Phase C deliverable [D2.0.6](https://app.zenhub.com/workspaces/lsstuk-project-mgmnt-5ee3ae947fc4e92804a2c64a/issues/gh/lsst-uk/ukdac_preops/95) and hence moving the due date.

**Comment by tms-epcc** [comment] 2024-01-25 13:48
25/JAN/24
- Change request [C091](https://lsst-uk.atlassian.net/wiki/download/attachments/751108134/C091_DR1_schedule_amendment.pdf?api=v2) approved at 22/JAN/25 Exec Group meeting
- CR deleted this deliverable

**Closed as completed** 2024-01-25 13:49 UTC
Labels: wontfix, Epic, deliverable
